category/urls.py
from django.conf.urls import url
from django.views.generic import DetailView

from .models import Category
from .views import CategoryAutoComplete
from .views import CategoryList

urlpatterns = [
    url(r'^$', CategoryList.as_view(), name='cats_list'),
    url(r'^category-autocomplete/$', CategoryAutoComplete.as_view(model=Category, create_field='title'),
        name='cat-autocomplete'),
    url(r'^(?P<slug>[-\w]+)/$', DetailView.as_view(model=Category, template_name='category.html',
                                                   slug_field='title'), name='cat_page'),

]

core/urls.py
from django.conf.urls import url

from .views import UserView

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', UserView.as_view(), name='user_page'),
]

event/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import NewEventView, EventView, EventUpdate

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', EventView.as_view(), name='event_page'),
    url(r'^new/$', login_required(NewEventView.as_view(), login_url='login'), name='new_event'),
    url(r'^(?P<pk>\d+)/update$', login_required(EventUpdate.as_view()), name='update_event')
]

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

from core.views import RegistrationView, IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^categories/', include('category.urls', namespace='cats')),
    url(r'^events/', include('event.urls', namespace='events')),
    url(r'^users/', include('core.urls', namespace='users')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(template_name='login.html', success_url='index'), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegistrationView.as_view(), name='register'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

core/models.py
import pycountry
from django.contrib.auth.models import AbstractUser
from django.db import models
from multiselectfield import MultiSelectField

countries = tuple((c.alpha_2, c.name) for c in pycountry.countries)
lang_list = tuple((l.alpha_3, l.name) for l in pycountry.languages)[:500]


class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True)
    languages = MultiSelectField(max_length=39, choices=lang_list, default='rus')
    country = models.CharField(max_length=2, choices=countries, default='RU')

core/forms.py
from dal import autocomplete
from django import forms

from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
        widgets = {'city': autocomplete.ModelSelect2(url='country-autocomplete')}

core/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import reverse
from django.views.generic import CreateView, DetailView, TemplateView

from event.models import Event


class MyUserCreation(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name',
                  'avatar', 'country', 'languages',)

    def save(self, commit=True):
        user = super(MyUserCreation, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.country = self.cleaned_data["country"]
        user.languages = self.cleaned_data["languages"]
        if commit:
            user.save()
        return user


class RegistrationView(CreateView):
    form_class = MyUserCreation
    template_name = 'register.html'

    def get_success_url(self):
        return reverse('index')


class UserView(DetailView):
    model = get_user_model()
    context_object_name = 'user'
    template_name = 'user_page.html'


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['events'] = Event.objects.all()
        return context

core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
            integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
            crossorigin="anonymous"></script>
    <link href="{% static "topbar-fixed.css" %}" rel="stylesheet">
    {% block additional %}
    {% endblock %}
    <title>
        {% block title %}
            Главная
        {% endblock %}
        - Поиск спутников
    </title>
</head>

<body style>
{% block menu %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Events site</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "index" %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.get_username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "events:new_event" %}">New event</a>
                            <a class="dropdown-item" href="{% url "users:user_page" pk=user.id %}">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url "logout" %}">Log out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "login" %}">Log in</a>
                    </li>
                {% endif %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "cats:cats_list" %}">Categories<span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
{% endblock %}
<main role="main" class="container">
{% block content %}
    <article>
        <a href="{% url "cats:cats_list" %}">All categories</a>
    </article>
{% endblock %}
</main>

{% include "footer.html" %}
</body>
</html>

core/templates/footer.html
<footer class="footer">
    Copyright © 2017
</footer>

core/templates/index.html
{% extends 'base.html' %} }

{% block content %}
    {% for event in  events %}
        <div>
            <a href="{% url "events:event_page" pk=event.id %}">{{ event.title }}</a><br>
        </div>
    {% endfor %}
{% endblock %}

core/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additional %}
    <link href="{% static "login.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign in">
    </form>
    <a href="{% url "register" %}">Sign up</a>
{% endblock %}

core/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
Enter your e-mail, login and password
</body>
</html>

core/templates/user_page.html
{% extends 'base.html' %}
{% block title %}
    Страница пользователя {{ user.username }}
{% endblock %}

{% block content %}
    {% for event in user.own_events.all %}
        <div>

        </div>
        <div>
            <a href="{% url "events:event_page" pk=event.id %}">{{ event.title }}</a>
        </div>
    {% endfor %}
{% endblock %}